{% set name = "xeus-robot" %}
{% set version = "0.3.1" %}
{% set build_number = 1 %}
{% if variant == 'default' %}
  {% set repo = "jupyter-xeus/xeus-robot" %}
  {% set sha256 = "b0327d1319d88fe330acf8a53d87c28455f028b41faa8f38ce7f6217e0633691" %}
{% else %}
  {% set repo = "jupyter-xeus/xeus-robot-wheel" %}
  {% set sha256 = "ebf8709deb2eb504a4cc5ed6a0eebbb68341b6766bf49828eec5fbe1a25ec18c" %}
{% endif %}

{% set pyver = PY_VER[0] + PY_VER[2] %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ repo }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}

outputs:
  - name: xeus-robot
{% if variant == 'default' %}
    script: build_default.sh   # [unix]
    script: build_default.bat  # [win]
{% else %}
    script: build_static.sh   # [unix]
    script: build_static.bat  # [win]
{% endif %}

    build:
      number: {{ build_number }}
      skip: true  # [py36]
{% if variant == 'default' %}
      string: py{{ pyver }}_{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
{% else %}
      string: static_py{{ pyver }}_{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
{% endif %}
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }}

    requirements:
      build:
{% if variant == 'default' %}
        - pybind11                               # [build_platform != target_platform]
{% else %}
        - pkg-config                             # [unix]
{% endif %}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make                                   # [unix]
      host:
        - python
{% if variant == 'default' %}
        - cppzmq >=4.7.1,<5
        - zeromq
        - xtl >=0.7.0,<0.8
        - xeus >=1.0.1,<2.0
        - xeus-python >=0.11.1,<0.12
        - pybind11 >=2.2.4,<3.0
        - nlohmann_json >=3.3.0,<4.0
        - pybind11_json >=0.2.2,<0.3
{% else %}
        - python
        - pip
        - scikit-build >=0.11.0,<0.12
        - libuuid  # [linux]
        - perl     # [win]
        - nasm     # [win]
{% endif %}
      run:
        - python
        - xeus-python >=0.11.1,<0.12
        - robotframework-interpreter  >=0.6.3,<0.7
        - robotframework-lsp
        - jupyterlab_robotmode
        - ipython >=7.20,<8
        - pygments >=2.3.1,<3
        - ipywidgets

    test:
      commands:
        - test -f ${PREFIX}/bin/xrobot                                                            # [unix]
        - test -f ${PREFIX}/share/jupyter/kernels/xrobot/kernel.json                              # [unix]
        - if not exist %LIBRARY_BIN%\\xrobot.exe (exit 1)                                         # [win]
        - if not exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xrobot\\kernel.json (exit 1)    # [win]
        # The kernel spec in installed in the general PREFIX
        - if not exist %PREFIX%\\share\\jupyter\\kernels\\xrobot\\kernel.json (exit 1)            # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-robot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for the Robot Framework based on Xeus
  description: xeus-robot is a Jupyter kernel for the Robot Framework based on the Xeus library, a native implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter-xeus/xeus-robot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
