{% set name = "xeus-robot" %}
{% set version = "0.3.0" %}
{% set sha256 = "ab89ad1f6310d1a041fd48edc30cc7281b0da8726d5cc822f392ac7d7da709cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-robot/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py36]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - cppzmq >=4.7.1,<5
    - zeromq
    - xtl >=0.7.0,<0.8
    - python
    - xeus >=1.0.1,<2.0
    - xeus-python >=0.11.1,<0.12
    - pybind11 >=2.2.4,<3.0
    - nlohmann_json >=3.3.0,<4.0
    - pybind11_json >=0.2.2,<0.3
  run:
    - python
    - xeus-python >=0.11.1,<0.12
    - robotframework-interpreter  >=0.6.3,<0.7
    - robotframework-lsp
    - jupyterlab_robotmode

test:
  commands:
    - test -f ${PREFIX}/bin/xrobot                                                            # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xrobot/kernel.json                              # [unix]
    - if not exist %LIBRARY_BIN%\\xrobot.exe (exit 1)                                         # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xrobot\\kernel.json (exit 1)    # [win]
    # The kernel spec in installed in the general PREFIX
    - if not exist %PREFIX%\\share\\jupyter\\kernels\\xrobot\\kernel.json (exit 1)            # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-robot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for the Robot Framework based on Xeus
  description: xeus-robot is a Jupyter kernel for the Robot Framework based on the Xeus library, a native implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter-xeus/xeus-robot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
