{% set name = "xeus-robot" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-robot/archive/{{ version }}.tar.gz          # [unix]
  sha256: "b0327d1319d88fe330acf8a53d87c28455f028b41faa8f38ce7f6217e0633691"            # [unix]
  url: https://github.com/jupyter-xeus/xeus-robot-wheel/archive/{{ version }}.tar.gz    # [win]
  sha256: "ebf8709deb2eb504a4cc5ed6a0eebbb68341b6766bf49828eec5fbe1a25ec18c"            # [win]

build:
  number: 1
  skip: true  # [py36]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - pybind11                               # [build_platform != target_platform and unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - make                                   # [unix]
  host:
    - pip
    - python
    - cppzmq >=4.7.1,<5                      # [unix]
    - zeromq                                 # [unix]
    - xtl >=0.7.0,<0.8                       # [unix]
    - xeus >=1.0.1,<2.0                      # [unix]
    - xeus-python >=0.11.1,<0.12             # [unix]
    - pybind11 >=2.2.4,<3.0                  # [unix]
    - nlohmann_json >=3.3.0,<4.0             # [unix]
    - pybind11_json >=0.2.2,<0.3             # [unix]
    - libuuid                                # [linux]
    - scikit-build >=0.11.0,<0.12            # [win]
    - perl                                   # [win]
    - nasm                                   # [win]
  run:
    - python
    - xeus-python >=0.11.1,<0.12
    - robotframework-interpreter  >=0.6.3,<0.7
    - robotframework-lsp
    - jupyterlab_robotmode
    - ipython >=7.20,<8
    - pygments >=2.3.1,<3
    - ipywidgets

test:
  commands:
    - test -f ${PREFIX}/bin/xrobot                                                            # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xrobot/kernel.json                              # [unix]
    - if not exist %LIBRARY_BIN%\\xrobot.exe (exit 1)                                         # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xrobot\\kernel.json (exit 1)    # [win]
    # The kernel spec in installed in the general PREFIX
    - if not exist %PREFIX%\\share\\jupyter\\kernels\\xrobot\\kernel.json (exit 1)            # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-robot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for the Robot Framework based on Xeus
  description: xeus-robot is a Jupyter kernel for the Robot Framework based on the Xeus library, a native implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter-xeus/xeus-robot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
